[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "Content-based Methods"
is_section = true
icon="ğŸ“š"

[[pages]]
path = "pages/10_Content_Filtering_Based_Recommendations.py"
name = "Plot Embeddings"
icon = ":pencil2:"

[[pages]]
name = "Collaborative Filtering Methods"
is_section = true
icon="ğŸ¤"

[[pages]]
path = "pages/20_Collaborative_Filtering_Based_Recommendations.py"
name = "Bipartite Graph"
icon = "ğŸ“Š"