[[pages]]
path = "ui/home.py"
name = "Home"
icon = ":house:"

[[pages]]
name = "Content Filtering Methods"
is_section = true
icon="ğŸ“š"

[[pages]]
path = "ui/plot_embeddings_method.py"
name = "Plot Embeddings"
icon = ":pencil2:"

[[pages]]
name = "Collaborative Filtering Methods"
is_section = true
icon="ğŸ¤"

[[pages]]
path = "ui/bipartite_graph_method.py"
name = "Bipartite Graph"
icon = "ğŸ“Š"

[[pages]]
name = "Content & Collaborative combined Methods"
is_section = true
icon="ğŸ“š"

[[pages]]
name = "Bipartite Graph + Plot Embeddings"
path = "ui/plot_embeddings_bipartite_combined.py"
icon = ":brain:"